import fs from 'fs';
import path from 'path';

const root = process.cwd();
const pkgPath = path.join(root, 'package.json');
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));

const outFile = path.join(root, 'src', 'consts.generated.ts');

const version = typeof pkg.version === 'string' ? pkg.version : '0.0.0';
const configFilename = 'sinker.config.js';

const content = `// This file is auto-generated by scripts/build-consts.mjs.
// Do not edit manually.
// Changes will be overwritten and lost at any time.

export const SINKER_VERSION: string = '${version}';
export const CONFIG_FILE: string = '${configFilename}';
`;

fs.writeFileSync(outFile, content, 'utf8');
console.log(`[prebuild] wrote ${path.relative(root, outFile)}`);
