// This file is auto-generated by scripts/build-consts.mjs.
// Do not edit manually.
// Changes will be overwritten and lost at any time.

export const SINKER_VERSION: string = '1.1.0';
export const CONFIG_FILE: string = 'sinker.config.js';
